Feat/wb2 1337 Add Routing for Note Modal
OPEN-ENT-NG/collaborative-wall pull request #25
Opened 2024-02-06 18:49 UTC by david-cc

Add route `note/:idnote` as children of main route`id/:id` to show Note Modal.
Data is loaded via a route loader executing a http request to the new API that returns note data by given idnote.

2024-02-07 09:08 UTC, ccreusat requested changes

2024-02-07 09:08 UTC, ccreusat commented on frontend/src/routes/collaborative-wall/index.tsx
@david-cc @Headan je vous laisse regarder, j'avais pas fait gaffe mais : 
- exporter le service dans le fichier `/services/api/index.ts` 
```
const collaborativeWall = odeServices
    .http()
    .get<CollaborativeWallProps>(`/collaborativewall/${id}`);
```

et normalement, il ne devrait pas y avoir de `notes/setNotes` pour les gérer => ça vient de la data
- gérer avec React Query s'il faut (voir blog@develop-b2school pour s'inspirer)
- si y'a besoin de partager entre 2 composants , ok pour le store zustand, mais voir si le props drilling est pas suffisant


merci

2024-02-07 09:08 UTC, ccreusat commented on frontend/src/routes/collaborative-wall/index.tsx
le useEffect pour mettre à jour les notes sert à rien .. c'est le `loader` qui doit le gérer 👍🏼

2024-02-08 16:04 UTC, david-cc commented on frontend/src/routes/collaborative-wall/index.tsx
@Headan s'occupera de ces retours sur une autre PR, je vais merge la PR

2024-02-08 16:04 UTC, merged