[EDIFICE] Ajout du temps réel
OPEN-ENT-NG/collaborative-wall pull request #57
Opened 2024-04-02 10:42 UTC by nabil-mansouri

Cette PR inclut le temps réel backend et le service front permettant de l'appeler
Il y a aussi un fallback http permettant de rendre le service utilisable pour les personnes n'ayant pas les websockets dispo

2024-04-02 14:52 UTC, juniorode requested changes

2024-04-02 14:52 UTC, juniorode commented on backend/src/main/java/net/atos/entng/collaborativewall/controllers/CollaborativeWallController.java
> +                    final String wsId = UUID.randomUUID().toString();
J'ai pas compris au début pourquoi tu générais un `wsId` ici mais en fait c'est pour contourner le fait que la méthode `pushEvent` plus bas en requiert un, nan ? Si c'est le cas, autant surcharger la méthode `pushEvent` (ou en créer une avec un nom explicite comme `pushEventToAllUsers` wui ne requiert pas de `wsId`.

2024-04-02 14:52 UTC, juniorode commented on backend/src/main/java/net/atos/entng/collaborativewall/controllers/CollaborativeWallController.java
> +                RequestUtils.bodyToJson(request, payload -> {
Tu peux utiliser ça plutôt https://github.com/edificeio/web-utils/blob/master/src/main/java/fr/wseduc/webutils/request/RequestUtils.java#L99 en lui passant `CollaborativeWallUserAction.class` comme paramètre

2024-04-02 14:52 UTC, juniorode commented on backend/src/main/java/net/atos/entng/collaborativewall/controllers/CollaborativeWallController.java
> +    private Optional<WallWebSocketController> webSocketController = Optional.empty();
J'ai des doutes sur la présence d'un controller dans un autre controller.
Pour pas être embêté au niveau de ce genre de dépendances j'avais pensé à des subscribers dans `CollaborativeWallRTService`. Comme ça y a que le verticle qui est au courant de cette dépendance.

2024-04-02 14:52 UTC, juniorode commented on backend/src/main/java/net/atos/entng/collaborativewall/controllers/WallWebSocketController.java
> +                            log.info("WS correctly removed");
ça je me dis qu'il faudrait le passer en DEBUG en fait pour pas être spammé

2024-04-02 14:52 UTC, juniorode commented on backend/src/main/java/net/atos/entng/collaborativewall/events/CollaborativeWallDetails.java
> +  private final JsonObject background;
`background` c'est une propriété un peu fourre-tout qui est tantôt une string tantôt un objet ou c'est toujours un objet ?

2024-04-02 14:52 UTC, juniorode commented on backend/src/main/java/net/atos/entng/collaborativewall/events/NoteMove.java
> +    private final Long x;
Pour éviter du boxing/unboxing je pense qu'on peut passer x et y en type primitif. COmme ça au moins ça pète si il nous manque l'un ou l'autre

2024-04-02 14:52 UTC, juniorode commented on backend/src/main/java/net/atos/entng/collaborativewall/service/impl/DefaultCollaborativeWallRTService.java
> +                // client has updated the image's note => upsert then broadcast to other users
Erreur dans le commentaire.

2024-04-02 15:16 UTC, nabil-mansouri commented on backend/src/main/java/net/atos/entng/collaborativewall/events/CollaborativeWallDetails.java
> +  private final JsonObject background;
yes ca sera toujours un objet car on va reprendre les données

2024-04-02 15:16 UTC, nabil-mansouri commented on backend/src/main/java/net/atos/entng/collaborativewall/events/NoteMove.java
> +    private final Long x;
j'avais peur des nullpointer mais c'est vrai autant que ça pète yes

2024-04-02 15:47 UTC, juniorode commented on backend/src/main/java/net/atos/entng/collaborativewall/events/CollaborativeWallDetails.java
> +  private final JsonObject background;
Du coup est-ce qu'on ne transformerait pas le cham background en classe typée plutôt qu'en JsonObject ?

2024-04-03 16:05 UTC, nabil-mansouri commented on backend/src/main/java/net/atos/entng/collaborativewall/controllers/CollaborativeWallController.java
> +    private Optional<WallWebSocketController> webSocketController = Optional.empty();
yes du coup  j'ai brisé la deps entre controller ca passe par le service avec les listeners qui sont écoutés par WallRTController

2024-04-04 09:02 UTC, nabil-mansouri commented on backend/src/main/java/net/atos/entng/collaborativewall/events/CollaborativeWallDetails.java
> +  private final JsonObject background;
du coup j'ai typé background dans les wall et media dans les notes

2024-04-04 12:02 UTC, juniorode approved these changes

2024-04-09 07:23 UTC, juniorode approved these changes

2024-04-16 13:09 UTC, merged